### ISSUE TITLE
DSLContextをAutowiredしたい

### ISSUE THREAD

**Issue by bigro** [bigro/matcheam#52]
https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-spring-boot-example/src
https://github.com/spring-projects/spring-boot/tree/af68993f71461dd15d1c7f8935b116e99c7b6dd1/spring-boot-samples/spring-boot-sample-jooq

**Comment by jnishida** [comment]
なぜかデフォルト接続になってしまう
