### ISSUE TITLE
EntryUserServiceのデータアクセス化

### ISSUE THREAD

**Issue by jnishida** [bigro/matcheam#84]

**Comment by jnishida** [comment]
人・事・物分析の途中までやった。

**Comment by jnishida** [comment]
クラス図書いた
https://files.slack.com/files-pri/T3136P1S5-F6FLXGCDT/image_uploaded_from_ios.jpg

**Comment by jnishida** [comment]
応募と応募者のテーブルの自動生成が成功したよ

**Comment by bigro** [comment]
EntryServiceになりました。

**Comment by bigro** [comment]
MySQLにしちゃったよ
